### PR TITLE
fix: use at least semantic-release/npm@3.2.2

### LINKED ISSUE #34: NPM_TOKEN Variable Unnecessarily Needed
When resolving https://github.com/crystal-lang-tools/atom-ide-crystal/issues/33 I discovered that adding a `NPM_TOKEN` environment is needed to function. A npm token is not needed to publish to apm. Without the environment variable the deploy errors out.

### PR DESCRIPTION
**Pull request by keplersj**
This version of the npm plugin includes a patch crucial to this config.

Fixes #34

### CODE REVIEW

**Comment by pvdlg** [comment]
The current range `^3.2.0` already include `3.2.2` (and the latest release which is `3.2.4`).
On each install `3.2.4` will be installed so what's the point of updating the dependency definition?

**Comment by Arcanemagus** [comment]
Because the current range _allows_ a broken installation. Your package should always work with the minimum versions of all packages listed, if not then the minimum version needs to be bumped 😉.

**Comment by pvdlg** [comment]
npm allow to have dependencies defined as a range in order to have non breaking changes installed automatically without having to update the dependency definition in `package.json`. This is a core feature of npm that allows to propagate fixes and feature quickly in the dependency tree without requiring to each package to consistently update its dependencies. As npm put it "npm is a bet on semver". This is the very reason for which the npm and Javascript ecosytem can evolve so fast.

Any patch release fixes a bug that is important for someone and which lack of result in a broken install for that person. If a fix doesn't fix something then it wouldn't be a fix. Having a dependency range that allow version that are not the latest will always result in a broken install for someone somewhere.

If we would apply the logic that the minimum version range defined for a dependency should not result in a broken install, then the dependency range defined should always enforces the latest version that contains all the fixes released to this date. That would completely defeat the purpose of using semver ranges for npm packages.

semver ranges is a really awesome part of npm because every time you do `npm install` you get all the latest fixes and that doesn't require package maintainer to constantly update their dependencies.
The entire concept of semantic-release is to embrace this feature and to make it safer by enforcing a proper version update of package during the release (`patch` for a fix, `minor` for new feature, `major` for a breaking change).

We have several request similar to this PR and I saw several on other projects as well. Everyone has a specific case in which their experience an issue due to a specific bug for which a fix exists. The proper solution for that, at least as intended by npm creator, is to run `npm update` to get the latest fixes, not to open PRs on every downstream dependency you are depending on.

Yes I could just click the merge button and yes it would way faster than writing this comment. However I feel like it's getting a more and more common practice to ask dependents projects to update their dependencies instead of just running `npm update`. As semantic-release is a project embracing and supporting semver it feels particularly wrong to give in this trend and I'd rather spend time to clarify how npm and semver ranges works and what's are their benefits.

In the present case, if I merge this PR and release a version `2.0.2` you will have to run `npm update` to get it in your local `npm_modules`. If I don't release a new version, you can still run `npm update` and that will get you the latest release of all the dependencies, therefore having the same effect.
Moreover semantic-release is run in the CI environment, so for every CI build `npm install` is run and downloads the latest in range versions of all the dependencies.

In the case where you use a lockfile, you make the conscious decision to lock outdated dependencies in order to have a consistent dependency tree across installs. Therefore it is your responsibility to update your lockfile once in a while to get the latest fixes. And even in that case merging this PR and releasing a version `2.0.2` will not solve this issue as you will still have to update your lockfile to get it.

**Comment by keplersj** [comment]
@pvdlg Thank you for explaining that. I was wrong to report #34 and open this PR. I've removed the package lock from the Atom package that I was having trouble with and my issues (predictably) have eased up.

It sounds to me that using a package lock with semantic-release should be highly discouraged. Is that written in the official documentation so that others don't have this issue?

**Comment by pvdlg** [comment]
> It sounds to me that using a package lock with semantic-release should be highly discouraged. Is that written in the official documentation so that others don't have this issue?

It's not something specific to semantic-release. If you are using a lockfile you will not get new fixes and features for any dependency. Whether you are using semantic-release or not your build might fail due to a fix you don't get because of your lockfile. It might affect anything from transpiling to linting or any build script.

Using a lockfile is a trade-off: you get a consistent dependency tree when running `npm install` at the root of the project at the price of not receiving any fixes or new features for your dependencies.
The benefits of using a lockfile might worth the inconvenient in some case. I personally never encountered a case in which a consistent dependency tree is valuable enough to accept not having the last dependencies fixes and features.

An other inconvenient of lockfile is the dependencies are only locked when you run `npm install` at the root of the project. Not when someone else use your project as a dependencies (shrinkwrap files do that but not `yarn.lock` and `package-lock.json`). So with a lockfile, you use a different dependency tree when you run your test than when users use your project.

The real problem here is that both Yarn and npm enable the lockfile by default and do not clearly explain users what trade-off they are making.
A benefit of lockfile is that hey allow fast installation (because the dependencies version are already determined) so I imagine if Yarn or npm would not enable lockfile by default or discourage to use them, it would trigger a tweetstorm of comment like "X is 5 time faster than Y". Even though comparing an installation that retrieve all the last versions with fixes and features and one that just install pre-determined version is unfair and inaccurate.

In the end, it's not up to semantic-release to recommend to use lockfiles or not. It's up to npm/Yarn to be clearer about the trade-off that comes with lockfile and to users to understand dependency resolution better.

**Pull request closed without merging**
